SECURITY_KEYWORDS = {
    "permission": "potential_access_check",
    "authorize": "potential_access_check",
    "authorization": "potential_access_check",
    "authentication": "potential_access_check",
    "access": "potential_access_check",
    "role": "potential_access_check",
    "policy": "potential_policy_file",
    "SecurityException": "potential_access_check",
    "checkPermission": "potential_access_check",
    "enforcePermission": "potential_access_check",
    "getCallingUid": "potential_entry_point",
    "getCallingUserId": "potential_entry_point",
    "hasSignatureCapability": "potential_helper",
    "Binder": "potential_entry_point",
    "SELinux": "potential_policy_file",
    "RBAC": "potential_access_check",
    "SubjectAccessReview": "potential_access_check",
    "AccessDenied": "potential_access_check",
    "Forbidden": "potential_access_check",
    "hasPermission": "potential_access_check",
    "hasRole": "potential_access_check",
    "hasAuthority": "potential_access_check",
    "authenticated": "potential_access_check",
    "requestMatchers": "potential_entry_point",
    "antMatchers": "potential_entry_point",
    "permitAll": "potential_access_check",
    "denyAll": "potential_access_check",
    "Depends": "potential_access_check",
    "Security": "potential_access_check",
    "HTTPBearer": "potential_access_check",
    "OAuth2PasswordBearer": "potential_access_check",
    "APIKeyHeader": "potential_access_check",
    "APIKeyCookie": "potential_access_check",
    "JWT": "potential_access_check",
    "jwt": "potential_access_check",
    "decode_token": "potential_helper",
    "create_access_token": "potential_helper",
    "get_current_user": "potential_helper",
    "get_current_active_user": "potential_helper",
    "require_role": "potential_access_check",
    "require_permission": "potential_access_check",
    "roles": "potential_access_check",
    "permissions": "potential_access_check",
    "is_admin": "potential_access_check",
    "admin_required": "potential_access_check",
    "HTTPException": "potential_access_check",
    "status.HTTP_401_UNAUTHORIZED": "potential_access_check",
    "status.HTTP_403_FORBIDDEN": "potential_access_check",
    "401": "potential_access_check",
    "403": "potential_access_check",
    "APIRouter": "potential_entry_point",
    "@app.get": "potential_entry_point",
    "@app.post": "potential_entry_point",
    "@router.get": "potential_entry_point",
    "@router.post": "potential_entry_point",
    "dependencies=": "potential_access_check",
    "scopes": "potential_access_check",
    "permission_classes": "potential_access_check",
    "IsAuthenticated": "potential_access_check",
    "IsAdminUser": "potential_access_check",
    "verify": "potential_helper",
    "sign": "potential_helper",
    "passport": "potential_access_check",
    "express-jwt": "potential_access_check",
    "requireAuth": "potential_access_check",
    "requireRole": "potential_access_check",
    "requirePermission": "potential_access_check",
    "middleware": "potential_helper",
    "isAdmin": "potential_access_check",
    "router.get": "potential_entry_point",
    "router.post": "potential_entry_point",
    "app.get": "potential_entry_point",
    "app.post": "potential_entry_point",
    "app.use": "potential_entry_point",
    "protect": "potential_access_check",
    "guard": "potential_access_check",
    "CanActivate": "potential_helper",
    "UseGuards": "potential_access_check",
    "AuthGuard": "potential_access_check",
    "JwtAuthGuard": "potential_access_check",
    "RolesGuard": "potential_access_check",
    "ForbiddenException": "potential_access_check",
    "UnauthorizedException": "potential_access_check",
}


def detect_security_tags(text: str, file_path: str = "") -> list[str]:
    haystack = f"{file_path}\n{text}"
    tags = {tag for keyword, tag in SECURITY_KEYWORDS.items() if keyword.lower() in haystack.lower()}
    suffix = file_path.lower()
    if suffix.endswith((".xml", ".json", ".yaml", ".yml", ".te")) and tags:
        tags.add("potential_config_file")
    return sorted(tags)


def confidence_for_tags(tags: list[str]) -> str:
    if len(tags) >= 3:
        return "High"
    if len(tags) >= 1:
        return "Medium"
    return "Low"
