import { expect, test, type Page } from "@playwright/test";

const evidence = [
  { chunk_id:"endpoint",file_path:"src/ProductController.java",symbol_name:"getProducts",start_line:8,end_line:12,language:"java",code_snippet:"@GetMapping\nvoid getProducts() {}",critical_lines:[9],final_score:1.26,retrieval_rank:1,evidence_priority_class:"target_primary",selected_file_match:true,http_method:"GET",security_tags:"authorization" },
  { chunk_id:"users",file_path:"src/WebSecurityConfig.java",symbol_name:"users",start_line:20,end_line:24,language:"java",code_snippet:"User.withUsername(\"demo\")",critical_lines:[21],final_score:1.1,retrieval_rank:2,evidence_priority_class:"required_supporting_role" },
];
const wikiContext = [{ chunk_id:"wiki:w1:0",wiki_id:"w1",title:"ProductController Security Wiki",section:"Access Control Matrix",source_focus:"src/ProductController.java",content:"Generated orientation",retrieval_rank:1 }];

async function mock(page: Page) {
  await page.addInitScript(() => localStorage.setItem("security_codewiki_token","test"));
  await page.route("**/api/models/health", r => r.fulfill({json:{ollama:{reachable:true,available:true,reason:"Ready",available_models:["qwen3.5:9b"],default_model:"qwen3.5:9b",default_model_exists:true,status:"Ready",base_url:"local"},gemini:{available:true,reason:"Ready",status:"Ready",api_key_configured:true,default_model_configured:true,default_model:"Gemini 2.5 Flash"},openai:{available:false,reason:"API key required",status:"Unavailable",api_key_configured:false,default_model_configured:true,default_model:"gpt-4o"},deepseek:{available:false,reason:"API key required",status:"Unavailable",api_key_configured:false,default_model_configured:true,default_model:"deepseek-chat"},embedding:{provider:"sentence-transformers",model:"bge",semantic:true,fallback_used:false,label:"Semantic"}}}));
  await page.route("**/api/projects/final/status", r => r.fulfill({json:{status:"indexed",status_message:"Ready",project:{id:"final",name:"Thesis Audit",source_type:"github",repo_url:"https://example/repo",local_path:"repo",commit_hash:"abc",status:"indexed",status_message:"Ready",files_indexed:15,chunks_indexed:58,created_at:"now",updated_at:"now"}}}));
  await page.route("**/api/projects/final/files/tree", r => r.fulfill({json:[{name:"src",path:"src",type:"directory",children:[{name:"ProductController.java",path:"src/ProductController.java",type:"file"},{name:"WebSecurityConfig.java",path:"src/WebSecurityConfig.java",type:"file"}]}]}));
  await page.route("**/api/projects/final/files/content?**", r => r.fulfill({json:{path:new URL(r.request().url()).searchParams.get("path"),content:Array.from({length:40},(_,i)=>`// line ${i+1}`).join("\n"),language:"java"}}));
  await page.route("**/api/projects/final/formal-runs", r => r.fulfill({json:[{run_id:"old",operation:"ask",question:"Where is access control enforced?",timestamp:new Date().toISOString(),provider_model_json:JSON.stringify({provider:"gemini",model:"Gemini 2.5 Flash"}),answer_json:JSON.stringify("**Historic answer**"),primary_evidence_json:JSON.stringify(evidence),wiki_context_json:JSON.stringify(wikiContext),execution_status:"Completed"}]}));
  await page.route("**/api/projects/final/wiki", async r => r.request().method()==="DELETE" ? r.fulfill({json:{deleted:true,message:"Deleted"}}) : r.fulfill({json:[{id:"w1",title:"ProductController Security Wiki",module_id:"src/ProductController.java",model_provider:"gemini",model_name:"Gemini 2.5 Flash",validation_status:"Ready",updated_at:"2026-08-12T15:42:00Z",content_markdown:"## Overview\n**Authorization** summary.\n\n| Name | File | Description |\n| --- | --- | --- |\n| getProducts | src/ProductController.java | endpoint |"}]}));
  await page.route("**/api/projects/final/wiki/**", r => r.fulfill({json:{deleted:true,message:"Deleted"}}));
  await page.route("**/api/projects/final/discover-security-modules", r => r.fulfill({json:[{module_path:"src/ProductController.java",language:"java",reason:"4 PreAuthorize matches",confidence:"High",security_tags:["authorization"],matching_symbols:["getProducts","addProduct","removeProduct"],matching_chunk_count:4,score:12},{module_path:"src/WebSecurityConfig.java",language:"java",reason:"Security configuration",confidence:"High",security_tags:["configuration"],matching_symbols:["users"],matching_chunk_count:1,score:9}]}));
  await page.route("**/api/projects/final/chat", r => r.fulfill({json:{message_id:"answer",answer:"## Result\n**Access control** is enforced here.\n\n- First check\n- Second check",evidence,wiki_context:wikiContext,context_used:"raw code + wiki context",validation_status:"completed",display_status:"Completed",provider:"gemini",model:"Gemini 2.5 Flash",execution:{execution_id:"ask",started_at:"now",completed_at:"now",operation:"ask",status:"completed",query:"q",provider:{provider:"gemini",model:"Gemini 2.5 Flash",request_duration_ms:7000,source_chunk_count:2,wiki_chunks_sent:1},retrieval:{vector_candidate_count:12,lexical_candidate_count:8,shared_evidence_hash:"hash"},processing:{parser:"json",parse_status:"valid"}}}}));
  const result=(provider:string,model:string,warning=false)=>({evaluation_id:`eval-${provider}`,provider,model,answer:`## ${provider} answer\n**Grounded** response`,latency_ms:provider==="gemini"?7000:29200,validation_status:warning?"completed_with_warnings":"completed",display_status:warning?"Completed with warnings":"Completed",shared_evidence_package_id:"pkg",shared_evidence_hash:"hash",serialized_chunk_ids:["endpoint","users"],evidence_package_match:true,warnings:warning?[{code:"invalid_model_file_reference",message:"One source-reference warning",claim:"Wrong.java"}]:[],evaluation_status:"not_scored",execution:{execution_id:provider,started_at:"now",completed_at:"now",operation:"compare",status:warning?"completed_with_warnings":"completed",query:"q",provider:{provider,model,request_duration_ms:provider==="gemini"?7000:29200,source_chunk_count:2,wiki_chunks_sent:1},retrieval:{vector_candidate_count:12,lexical_candidate_count:8,shared_evidence_hash:"hash"},processing:{parser:"json",parse_status:"valid"}}});
  await page.route("**/api/projects/final/compare-models", r => r.fulfill({json:{question:"q",evidence,wiki_context:wikiContext,comparison_valid:true,rq2_comparison_eligible:true,comparison_model_count:2,shared_wiki_context_hash:"wiki-hash",shared_evidence_package_id:"pkg",shared_evidence_hash:"hash",results:[result("gemini","Gemini 2.5 Flash"),result("ollama","qwen3.5:9b",true)],run_summary:{execution_id:"compare",question:"q",shared_evidence_package_id:"pkg",shared_evidence_hash:"hash",shared_wiki_context_hash:"wiki-hash",comparison_valid:true,rq2_comparison_eligible:true,comparison_model_count:2,started_at:"now",completed_at:"now",total_duration:36200,selected_models:[{provider:"gemini",model:"Gemini 2.5 Flash"},{provider:"ollama",model:"qwen3.5:9b"}]}}}));
  await page.route("**/api/projects/final/evaluations/**", r => r.fulfill({json:{saved:true}}));
  await page.goto("/projects/final"); await expect(page.locator(".product-shell")).toBeVisible();
}
async function focus(page:Page){await page.getByLabel("Discovery search").fill("roles");await page.getByRole("button",{name:"Search"}).click();await page.getByRole("button",{name:"Focus analysis"}).first().click();}
async function ask(page:Page){await page.getByRole("button",{name:"Ask",exact:true}).click();await page.getByLabel("Question").fill("Where?");await page.getByRole("button",{name:"Run analysis"}).click();await expect(page.getByText("Access control",{exact:true})).toBeVisible();}
async function compare(page:Page){await page.getByRole("button",{name:"Compare",exact:true}).click();await page.getByLabel("Question").fill("Compare this");await page.getByRole("button",{name:"Compare models"}).click();await expect(page.locator(".model-answer")).toHaveCount(2);}

test.beforeEach(async({page})=>mock(page));
test("1 no Overview primary tab",async({page})=>{await expect(page.getByRole("button",{name:"Overview",exact:true})).toHaveCount(0);await expect(page.locator(".primary-nav button")).toHaveText(["Discover","Security Wikis","Ask","Compare","History"])});
test("2 global model selector visible across workflows",async({page})=>{for(const name of ["Discover","Security Wikis","Ask","Compare","History"]){await page.getByRole("button",{name,exact:true}).click();await expect(page.getByLabel("Default model")).toBeVisible()}});
test("3 Analysis focus persists across tabs",async({page})=>{await focus(page);await page.getByRole("button",{name:"Ask",exact:true}).click();await expect(page.locator(".app-header")).toContainText("ProductController.java")});
test("4 Discovery search is single-line",async({page})=>{await expect(page.getByLabel("Discovery search")).toHaveJSProperty("tagName","INPUT")});
test("5 Discovery Filters opens compact controls",async({page})=>{await page.getByRole("button",{name:"Filters"}).click();await expect(page.getByRole("region",{name:"Discover filters"})).toBeVisible();await expect(page.getByText(/Discover results only/)).toBeVisible()});
test("6 Focus analysis updates global focus",async({page})=>{await focus(page);await expect(page.locator(".global-focus")).toContainText("ProductController.java")});
test("7 Wiki library lists view and delete",async({page})=>{await page.getByRole("button",{name:"Security Wikis"}).click();await expect(page.getByText("ProductController Security Wiki")).toBeVisible();await page.getByRole("button",{name:"View"}).click();await expect(page.getByText("Authorization",{exact:true})).toBeVisible();await page.getByRole("button",{name:"All Wikis"}).click();page.once("dialog",d=>d.accept());await page.getByRole("button",{name:/Delete/}).click();await expect(page.getByText("ProductController Security Wiki")).toHaveCount(0)});
test("8 Ask renders Markdown without literal markers",async({page})=>{await ask(page);await expect(page.locator(".answer-panel .markdown h2, .answer-panel .markdown h3")).toContainText("Result");await expect(page.locator(".answer-panel")).not.toContainText("**")});
test("9 Evidence opens Monaco exact lines",async({page})=>{await ask(page);await page.getByRole("button",{name:/Open source/}).first().click();await expect(page.locator(".source-breadcrumb")).toContainText("lines 8–12");await expect(page.locator(".evidence-line-highlight").first()).toBeVisible();await expect(page.locator(".critical-line-highlight").first()).toBeVisible()});
test("10 raw ranking score hidden by default",async({page})=>{await ask(page);await expect(page.getByText(/Raw ranking score/).first()).not.toBeVisible();await page.getByText("Why selected").first().click();await page.getByText("Advanced retrieval details").first().click();await expect(page.getByText("Raw ranking score:").first()).toBeVisible()});
test("11 Wiki context shows selected sections only",async({page})=>{await ask(page);await expect(page.getByText("1 related Wiki sections used")).toBeVisible();await page.getByText("Security Wiki context").click();await expect(page.getByText("Access Control Matrix")).toBeVisible()});
test("12 Compare shows two answers and one shared evidence list",async({page})=>{await compare(page);await expect(page.locator(".model-answer")).toHaveCount(2);await expect(page.getByText("Shared primary evidence")).toHaveCount(1)});
test("13 unavailable models disabled",async({page})=>{await page.getByRole("button",{name:"Compare",exact:true}).click();await expect(page.getByLabel(/OpenAI/)).toBeDisabled();await expect(page.getByLabel(/DeepSeek/)).toBeDisabled()});
test("14 Run details summary and advanced diagnostics",async({page})=>{await ask(page);await page.getByText("Run details").click();await expect(page.getByText("7.0 seconds")).toBeVisible();await page.getByText("Advanced technical diagnostics").click();await expect(page.getByText(/vector_candidate_count/)).toBeVisible()});
test("15 History item restores run",async({page})=>{await page.getByRole("button",{name:"History",exact:true}).click();await page.locator(".history-item").first().click();await expect(page.getByRole("heading",{name:"Ask"})).toBeVisible();await expect(page.getByText("Historic answer")).toBeVisible()});
test("16 evaluation collapsed by default",async({page})=>{await ask(page);await expect(page.locator(".evaluation-panel[open]")).toHaveCount(0);await expect(page.getByText("Evaluate result")).toBeVisible()});
test("17 Export available from global action",async({page})=>{await page.getByLabel("Export").click();await expect(page.getByRole("button",{name:"HTML report / Print as PDF"})).toBeVisible()});
for(const [id,width,height] of [[18,1920,1080],[19,1366,768],[20,1024,768],[21,390,844]] as const)test(`${id} responsive ${width}x${height}`,async({page})=>{await page.setViewportSize({width,height});await ask(page);await expect(page.locator(".workflow-page")).toBeVisible();await page.screenshot({path:`e2e/screenshots/workspace-${width}x${height}.png`,fullPage:true})});
