import { expect, test, type Page } from "@playwright/test";

const evidence=[{chunk_id:"e1",file_path:"src/ProductController.java",symbol_name:"getProducts",start_line:8,end_line:12,language:"java",code_snippet:"@GetMapping",critical_lines:[9],final_score:1.2,evidence_priority_class:"target_primary"}];
const wikiContext=[{chunk_id:"wiki:w1:0",title:"ProductController Security Wiki",section:"Entry Points",source_focus:"src/ProductController.java",retrieval_rank:1}];
const execution=(provider:string,model:string,status="completed")=>({execution_id:`x-${provider}`,started_at:"now",completed_at:"now",operation:"compare",status,query:"q",provider:{provider,model,request_duration_ms:8400,source_chunk_count:1,wiki_chunks_sent:1},retrieval:{vector_candidate_count:4},processing:{parser:"json"}});
const result=(provider:string,model:string,status="completed")=>({evaluation_id:`eval-${provider}`,provider,model,answer:status==="provider_unavailable"?`${provider} could not complete the request.`:`## ${provider} answer\nGrounded response`,latency_ms:8400,validation_status:status,display_status:status==="provider_unavailable"?"Failed":"Completed",evidence_package_match:true,serialized_chunk_ids:["e1"],warnings:[],execution:execution(provider,model,status),error:status==="provider_unavailable"?{user_message:`${provider} request timed out.`}:null});

async function setup(page:Page,{failure=false,longName=false}:{failure?:boolean,longName?:boolean}={}){
 await page.addInitScript(()=>localStorage.setItem("security_codewiki_token","test"));
 await page.route("**/api/models/health",r=>r.fulfill({json:{gemini:{available:true,status:"Ready",reason:"Ready",default_model:"gemini-2.5-flash",api_key_configured:true,default_model_configured:true},ollama:{available:true,status:"Ready",reason:"Ready",default_model:"qwen3.5:9b",available_models:["qwen3.5:9b"],default_model_exists:true,reachable:true,base_url:"local"},openai:{available:true,status:"Ready",reason:"Ready",default_model:"gpt-4o",api_key_configured:true,default_model_configured:true},deepseek:{available:false,status:"Unavailable",reason:"API key required",default_model:"deepseek",api_key_configured:false,default_model_configured:true},embedding:{provider:"sentence",model:"bge",semantic:true,fallback_used:false,label:"Semantic"}}}));
 await page.route("**/api/projects/stable/status",r=>r.fulfill({json:{status:"indexed",status_message:"Ready",project:{id:"stable",name:"Stable Audit",source_type:"github",local_path:"repo",status:"indexed",status_message:"Ready",files_indexed:15,chunks_indexed:58,created_at:"now",updated_at:"now"}}}));
 const filename=longName?"ExtremelyLongProductAuthorizationControllerImplementationThatMustRemainReadable.java":"ProductController.java";
 await page.route("**/api/projects/stable/files/tree",r=>r.fulfill({json:[{name:"src",path:"src",type:"directory",children:[{name:filename,path:`src/${filename}`,type:"file"},{name:"ProductController.java",path:"src/ProductController.java",type:"file"}]}]}));
 await page.route("**/api/projects/stable/files/content?**",r=>r.fulfill({json:{path:new URL(r.request().url()).searchParams.get("path"),content:Array.from({length:40},(_,i)=>`// line ${i+1}`).join("\n"),language:"java"}}));
 const wiki={id:"w1",title:"ProductController Security Wiki",module_id:"src/ProductController.java",updated_at:"2026-08-12T15:42:00Z",content_markdown:"## Overview\nSecurity summary.\n\n## Entry Points\n| Name | File | Lines | Description |\n| --- | --- | --- | --- |\n| getProducts | src/ProductController.java | 8-12 | Protected endpoint with a useful longer description |"};
 await page.route("**/api/projects/stable/wiki",r=>r.fulfill({json:[wiki]}));
 const compareResults=[result("gemini","gemini-2.5-flash",failure?"provider_unavailable":"completed"),result("ollama","qwen3.5:9b"),result("openai","gpt-4o")];
 const compareMeta={execution_id:"compare-run",question:"Compare question",shared_evidence_package_id:"pkg",shared_evidence_hash:"hash",shared_wiki_context_hash:"whash",comparison_valid:!failure,rq2_comparison_eligible:!failure,comparison_model_count:2,completed_model_count:failure?1:2,started_at:"2026-08-12T15:40:00Z",completed_at:"2026-08-12T15:40:17Z",total_duration:16800,selected_models:[{provider:"gemini",model:"gemini-2.5-flash"},{provider:"ollama",model:"qwen3.5:9b"}]};
 const formal=[
  {run_id:"ask-old",operation:"ask",question:"Historic Ask question",timestamp:new Date().toISOString(),provider_model_json:JSON.stringify({provider:"gemini",model:"gemini-2.5-flash"}),answer_json:JSON.stringify("Historic Ask answer"),primary_evidence_json:JSON.stringify(evidence),wiki_context_json:JSON.stringify(wikiContext),execution_status:"Completed"},
  {run_id:"compare-old",operation:"compare",question:"Historic Compare question",timestamp:new Date().toISOString(),provider_model_json:JSON.stringify(compareMeta.selected_models),answer_json:JSON.stringify(compareResults.slice(0,2)),primary_evidence_json:JSON.stringify(evidence),wiki_context_json:JSON.stringify(wikiContext),comparison_metadata_json:JSON.stringify(compareMeta),execution_status:"Completed"},
  {run_id:"wiki-old",operation:"wiki",question:"src/ProductController.java",timestamp:new Date().toISOString(),provider_model_json:JSON.stringify({provider:"gemini",model:"gemini-2.5-flash"}),answer_json:JSON.stringify(wiki.content_markdown),primary_evidence_json:"[]",wiki_context_json:"[]",execution_status:"Ready"}
 ];
 await page.route("**/api/projects/stable/formal-runs",r=>r.fulfill({json:formal}));
 await page.route("**/api/projects/stable/discover-security-modules",r=>r.fulfill({json:[{module_path:"src/ProductController.java",language:"java",reason:"Authorization annotations",confidence:"High",security_tags:["authorization"],matching_symbols:["getProducts"],score:10}]}));
 await page.route("**/api/projects/stable/chat",r=>r.fulfill({json:{message_id:"a",answer:"## Answer\nGrounded",evidence,wiki_context:wikiContext,validation_status:"completed",display_status:"Completed",provider:"gemini",model:"gemini-2.5-flash",execution:execution("gemini","gemini-2.5-flash")}}));
 await page.route("**/api/projects/stable/compare-models",async r=>{const body=await r.request().postDataJSON();const selected=body.providers as string[];const selectedResults=compareResults.filter(item=>selected.includes(item.provider));await r.fulfill({json:{question:body.question,evidence,wiki_context:wikiContext,results:selectedResults,comparison_valid:!failure&&selectedResults.length>=2,rq2_comparison_eligible:!failure&&selectedResults.length>=2,comparison_model_count:selectedResults.length,run_summary:{...compareMeta,comparison_model_count:selectedResults.length,selected_models:compareMeta.selected_models.filter(item=>selected.includes(item.provider)),comparison_valid:!failure&&selectedResults.length>=2,rq2_comparison_eligible:!failure&&selectedResults.length>=2}}})});
 await page.goto("/projects/stable");await expect(page.locator(".product-shell")).toBeVisible();
}
async function chooseFocus(page:Page){await page.getByLabel("Discovery search").fill("auth");await page.getByRole("button",{name:"Search"}).click();await page.getByRole("button",{name:"Focus analysis"}).click()}
async function runCompare(page:Page){await page.getByRole("button",{name:"Compare",exact:true}).click();await page.locator('textarea[aria-label="Question"]').fill("Compare question");await page.getByRole("button",{name:"Compare models"}).click()}
async function runAsk(page:Page){await page.getByRole("button",{name:"Ask",exact:true}).click();await page.locator('textarea[aria-label="Question"]').fill("Ask question");await page.getByRole("button",{name:"Run analysis"}).click()}

test("Gemini and Qwen selected return two differentiated results and matching summary",async({page})=>{await setup(page);await runCompare(page);await expect(page.locator(".model-answer")).toHaveCount(2);await expect(page.locator(".model-answer").nth(0)).toContainText("gemini-2.5-flash");await expect(page.locator(".model-answer").nth(1)).toContainText("qwen3.5:9b");await expect(page.locator(".integrity")).toContainText("2 models");await expect(page.locator(".integrity")).toContainText("RQ2 eligible")});
test("selected model failure remains visible",async({page})=>{await setup(page,{failure:true});await runCompare(page);await expect(page.locator(".model-answer")).toHaveCount(2);await expect(page.locator(".model-answer.failed")).toContainText("Could not complete the request");await expect(page.locator(".model-answer.failed")).toContainText("timed out");await expect(page.locator(".integrity")).toContainText("Not RQ2 eligible")});
test("Compare summary count matches selected executions",async({page})=>{await setup(page);await runCompare(page);await expect(page.locator(".integrity")).toContainText("2 models");await expect(page.locator(".model-answer")).toHaveCount(2)});
test("RQ2 eligibility uses completed result count",async({page})=>{await setup(page,{failure:true});await runCompare(page);await expect(page.locator(".model-answer")).toHaveCount(2);await expect(page.locator(".integrity")).toContainText("Not RQ2 eligible")});
test("three ready models produce three result records",async({page})=>{await setup(page);await page.getByRole("button",{name:"Compare",exact:true}).click();await page.getByLabel(/OpenAI/).check();await page.locator('textarea[aria-label="Question"]').fill("Three");await page.getByRole("button",{name:"Compare models"}).click();await expect(page.locator(".model-answer")).toHaveCount(3)});
test("clear Analysis focus works and persists across tabs",async({page})=>{await setup(page);await chooseFocus(page);await page.getByLabel("Clear analysis focus").click();await expect(page.locator(".global-focus")).toContainText("None");await page.getByRole("button",{name:"Ask",exact:true}).click();await expect(page.locator(".composer-meta")).toContainText("None");await page.getByRole("button",{name:"Security Wikis"}).click();await expect(page.getByText("Select an analysis focus before generating a Security Wiki.")).toBeVisible()});
test("History Ask restores Ask question and answer",async({page})=>{await setup(page);await page.getByRole("button",{name:"History"}).click();await page.getByText(/Historic Ask question/).click();await expect(page.getByRole("heading",{name:"Ask"})).toBeVisible();await expect(page.locator('textarea[aria-label="Question"]')).toHaveValue("Historic Ask question");await expect(page.getByText("Historic Ask answer")).toBeVisible()});
test("History Compare restores Compare question results and models",async({page})=>{await setup(page);await page.getByRole("button",{name:"History"}).click();await page.getByText(/Historic Compare question/).click();await expect(page.getByRole("heading",{name:"Compare"})).toBeVisible();await expect(page.locator('textarea[aria-label="Question"]')).toHaveValue("Historic Compare question");await expect(page.locator(".model-answer")).toHaveCount(2);await expect(page.getByLabel(/Gemini/)).toBeChecked();await expect(page.getByLabel(/Local Ollama/)).toBeChecked()});
test("History Wiki opens matching Security Wiki detail",async({page})=>{await setup(page);await page.getByRole("button",{name:"History"}).click();await page.getByText(/src\/ProductController.java/).click();await expect(page.getByText("← All Wikis")).toBeVisible();await expect(page.getByText("Security summary.")).toBeVisible()});
test("Monaco is dark and evidence exact line highlights remain",async({page})=>{await setup(page);await runAsk(page);await page.locator(".evidence-row > button").first().click();await expect(page.locator(".monaco-editor")).toHaveCSS("background-color","rgb(30, 30, 30)");await expect(page.locator(".source-breadcrumb")).toContainText("lines 8–12");await expect(page.locator(".evidence-line-highlight").first()).toBeVisible();await expect(page.locator(".critical-line-highlight").first()).toBeVisible();await expect(page.getByText("Grounded",{exact:true})).toBeVisible()});
test("Wiki source opens dark Monaco at exact lines",async({page})=>{await setup(page);await page.getByRole("button",{name:"Security Wikis"}).click();await page.getByRole("button",{name:"View"}).click();await page.getByRole("button",{name:"Open source"}).click();await expect(page.locator(".monaco-editor")).toHaveCSS("background-color","rgb(30, 30, 30)");await expect(page.locator(".evidence-line-highlight").first()).toBeVisible()});
test("sidebar collapse and reopen preserves width",async({page})=>{await setup(page);const before=await page.locator(".file-sidebar").boundingBox();await page.getByLabel("Collapse project files").click();await expect(page.locator(".file-sidebar")).toBeHidden();await page.getByLabel("Toggle project files").click();await expect(page.locator(".file-sidebar")).toBeVisible();const after=await page.locator(".file-sidebar").boundingBox();expect(after?.width).toBe(before?.width)});
test("long filenames ellipsize with full path tooltip and no page overflow",async({page})=>{await setup(page,{longName:true});const item=page.locator(".file-tree button").first();await expect(item).toHaveAttribute("title",/ExtremelyLong/);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow).toBe(false)});

test("capture required visual validation matrix",async({page})=>{await setup(page);for(const [width,height] of [[1920,1080],[1366,768],[1024,768]]){await page.setViewportSize({width,height});await page.getByRole("button",{name:"Discover"}).click();await page.getByLabel("Discovery search").fill("authorization");await page.getByRole("button",{name:"Search"}).click();await expect(page.getByRole("button",{name:"Focus analysis"})).toBeVisible();await page.screenshot({path:`e2e/screenshots/post-ux-${width}x${height}-discover.png`,fullPage:true});await page.getByRole("button",{name:"Security Wikis"}).click();await page.getByRole("button",{name:"View"}).click();await page.screenshot({path:`e2e/screenshots/post-ux-${width}x${height}-wiki-detail.png`,fullPage:true});await page.getByText("← All Wikis").click();await runAsk(page);await expect(page.getByText("Grounded",{exact:true})).toBeVisible();await page.locator(".evidence-row > button").first().click();await expect(page.locator(".monaco-editor")).toBeVisible();await page.screenshot({path:`e2e/screenshots/post-ux-${width}x${height}-ask-source.png`,fullPage:true});await page.getByLabel("Close source").click();await runCompare(page);await expect(page.locator(".model-answer")).toHaveCount(2);await page.screenshot({path:`e2e/screenshots/post-ux-${width}x${height}-compare.png`,fullPage:true});await page.getByRole("button",{name:"History"}).click();await expect(page.getByRole("heading",{name:"History"})).toBeVisible();await page.screenshot({path:`e2e/screenshots/post-ux-${width}x${height}-history.png`,fullPage:true})}});
