import { expect, test, type Page } from "@playwright/test";

const localStorage = { clear: () => undefined };

const project={id:"visual",name:"Access Control Study",source_type:"github",repo_url:"https://github.com/example/security-app",local_path:"repo",status:"indexed",status_message:"Indexing completed without errors.",files_indexed:15,chunks_indexed:58,created_at:"2026-08-10T10:00:00Z",updated_at:"2026-08-12T10:00:00Z"};
const evidence=[{chunk_id:"e1",file_path:"src/main/java/com/example/security/controller/ProductController.java",symbol_name:"getProducts",start_line:8,end_line:12,language:"java",code_snippet:"@GetMapping",critical_lines:[9],evidence_priority_class:"target_primary"}];
const wiki={id:"w1",title:"ProductController Security Wiki",module_id:evidence[0].file_path,model_provider:"gemini",model_name:"gemini-2.5-flash",validation_status:"Ready",updated_at:"2026-08-12T15:42:00Z",content_markdown:"## Overview\nProductController exposes protected product operations and delegates authorization-aware work.\n\n## Entry Points\n| Name | File | Lines | Description |\n| --- | --- | --- | --- |\n| getProducts | src/main/java/com/example/security/controller/ProductController.java | 8-12 | Returns products after the configured security chain authorizes the request. |\n\n## Access Control Matrix\n| Action | Requirement | Source |\n| --- | --- | --- |\n| List products | Authenticated user | src/main/java/com/example/security/controller/ProductController.java |\n\n## Vertical Helpers\n- ProductService — Business-logic dependency\n\n## Requirement Traces\n- Requirement: authenticated access; Enforcement: security configuration; Source: ProductController.java\n\n## Limitations\n- Generated orientation must be verified against primary source evidence."};
const execution={execution_id:"x1",started_at:"now",completed_at:"now",operation:"ask",status:"completed",query:"auth",provider:{provider:"gemini",model:"gemini-2.5-flash",request_duration_ms:1400,source_chunk_count:1,wiki_chunks_sent:1}};

async function commonRoutes(page:Page){
  await page.route("**/api/auth/login",async r=>{const body=await r.request().postDataJSON();body.password==="bad"?await r.fulfill({status:401,json:{detail:"Invalid username or password"}}):await r.fulfill({json:{access_token:"test",token_type:"bearer"}})});
  await page.route("**/api/projects",async r=>r.request().method()==="POST"?r.fulfill({json:project}):r.fulfill({json:[project]}));
  await page.route("**/api/projects/android-case-studies",r=>r.fulfill({json:[{id:"account-manager-service",name:"Account Manager",hint:"Curated"}]}));
  await page.route("**/api/models/health",r=>r.fulfill({json:{gemini:{available:true,status:"Ready",default_model:"gemini-2.5-flash"},ollama:{available:true,status:"Ready",default_model:"qwen3.5:9b",available_models:["qwen3.5:9b"]},openai:{available:false,status:"Unavailable",reason:"API key required"},deepseek:{available:false,status:"Unavailable",reason:"API key required"}}}));
  await page.route("**/api/projects/visual/status",r=>r.fulfill({json:{status:"indexed",status_message:"Ready",project}}));
  await page.route("**/api/projects/visual/files/tree",r=>r.fulfill({json:[{name:"src",path:"src",type:"directory",children:[{name:"main",path:"src/main",type:"directory",children:[{name:"java",path:"src/main/java",type:"directory",children:[{name:"com",path:"src/main/java/com",type:"directory",children:[{name:"example",path:"src/main/java/com/example",type:"directory",children:[{name:"security",path:"src/main/java/com/example/security",type:"directory",children:[{name:"controller",path:"src/main/java/com/example/security/controller",type:"directory",children:[{name:"ProductController.java",path:evidence[0].file_path,type:"file"},{name:"WebSecurityConfigurationWithReadableLongFilename.java",path:"src/main/java/com/example/security/controller/WebSecurityConfigurationWithReadableLongFilename.java",type:"file"}]}]}]}]}]}]}]}]}));
  await page.route("**/api/projects/visual/files/content?**",r=>r.fulfill({json:{path:evidence[0].file_path,content:Array.from({length:30},(_,i)=>`// line ${i+1}`).join("\n"),language:"java"}}));
  await page.route("**/api/projects/visual/wiki",r=>r.fulfill({json:[wiki]}));
  await page.route("**/api/projects/visual/formal-runs",r=>r.fulfill({json:[]}));
  await page.route("**/api/projects/visual/discover-security-modules",r=>r.fulfill({json:[{module_path:evidence[0].file_path,language:"java",reason:"Authorization annotations",confidence:"High",matching_symbols:["getProducts"]}]}));
  await page.route("**/api/projects/visual/chat",r=>r.fulfill({json:{message_id:"m1",answer:"## Answer\nGrounded response",evidence,wiki_context:[],provider:"gemini",model:"gemini-2.5-flash",validation_status:"completed",execution}}));
  await page.route("**/api/projects/visual/compare-models",r=>r.fulfill({json:{question:"Compare",evidence,wiki_context:[],results:[{evaluation_id:"g",provider:"gemini",model:"gemini-2.5-flash",answer:"Gemini answer",validation_status:"completed",evidence_package_match:true,warnings:[],execution},{evaluation_id:"q",provider:"ollama",model:"qwen3.5:9b",answer:"Qwen answer",validation_status:"completed",evidence_package_match:true,warnings:[],execution:{...execution,provider:{...execution.provider,provider:"ollama",model:"qwen3.5:9b"}}}],rq2_comparison_eligible:true,comparison_model_count:2,run_summary:{execution_id:"c1",question:"Compare",shared_evidence_package_id:"p",shared_evidence_hash:"h",shared_wiki_context_hash:"w",comparison_valid:true,rq2_comparison_eligible:true,comparison_model_count:2,selected_models:[{provider:"gemini",model:"gemini-2.5-flash"},{provider:"ollama",model:"qwen3.5:9b"}]}}}));
}
async function workspace(page:Page){await commonRoutes(page);await page.addInitScript(()=>localStorage.setItem("security_codewiki_token","test"));await page.goto("/projects/visual");await expect(page.locator(".product-shell")).toBeVisible()}
async function discover(page:Page){await page.getByLabel("Discovery search").fill("authorization");await page.getByRole("button",{name:"Search"}).click()}

test("login renders, errors, submits, and keeps accessible password control",async({page})=>{await commonRoutes(page);await page.goto("/login");await expect(page.getByText("Evidence-first source audit workspace")).toBeVisible();const password=page.getByRole("textbox",{name:"Password"});await password.fill("bad");await page.getByRole("button",{name:"Sign in"}).click();await expect(page.getByRole("alert")).toContainText(/invalid/i);await password.fill("valid");await page.getByRole("button",{name:"Show password"}).click();await expect(password).toHaveAttribute("type","text");await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL("/")});
test("project source selection, creation, opening, and removal remain wired",async({page})=>{await commonRoutes(page);await page.addInitScript(()=>localStorage.setItem("security_codewiki_token","test"));await page.goto("/");await page.getByRole("button",{name:"ZIP"}).click();await expect(page.getByText("ZIP Upload")).toBeVisible();await page.getByRole("button",{name:"Android"}).click();await expect(page.getByText("Android Case Study")).toBeVisible();await page.getByRole("button",{name:"GitHub"}).click();await page.getByLabel("Project name").fill("New Study");await page.getByLabel("Repository URL").fill("https://github.com/example/repo");await page.getByRole("button",{name:"Create Project"}).click();await expect(page).toHaveURL(/projects\/visual/);await page.goto("/");await page.getByRole("button",{name:"Access Control Study"}).click();await expect(page).toHaveURL(/projects\/visual/);await page.goto("/");page.once("dialog",d=>d.dismiss());await page.getByLabel("Actions for Access Control Study").click();await page.getByRole("button",{name:"Remove project"}).click()});
test("sidebar hierarchy, tooltip, file opening, and collapse work",async({page})=>{await workspace(page);const folders=page.locator(".file-tree details");await expect(folders).toHaveCount(7);const root=page.getByTitle("src",{exact:true});await root.click();await expect(page.getByTitle(evidence[0].file_path)).toBeHidden();await root.click();const file=page.getByTitle(evidence[0].file_path);await expect(file).toBeVisible();await file.click();await expect(page.locator(".monaco-editor")).toBeVisible();await page.getByLabel("Close source").click();await page.getByLabel("Collapse project files").click();await expect(page.locator(".file-sidebar")).toBeHidden();await page.getByLabel("Toggle project files").click();await expect(page.locator(".file-sidebar")).toBeVisible();const width=await page.getByTitle("src/main/java/com/example/security/controller/WebSecurityConfigurationWithReadableLongFilename.java").evaluate(el=>({client:el.clientWidth,text:(el.querySelector("span") as HTMLElement).scrollWidth}));expect(width.client).toBeGreaterThan(100);expect(width.text).toBeGreaterThan(width.client)});
test("Discover has a local clear-focus action and can restore focus",async({page})=>{await workspace(page);await discover(page);await page.getByRole("button",{name:"Focus analysis"}).click();await expect(page.getByLabel("Clear Discover analysis focus")).toBeVisible();await page.getByLabel("Clear Discover analysis focus").click();await expect(page.getByText("No file selected")).toBeVisible();await page.getByRole("button",{name:"Focus analysis"}).click();await expect(page.locator(".focus-banner")).toContainText("ProductController.java")});
test("Wiki sections are visible as cards and source navigation remains exact",async({page})=>{await workspace(page);await page.getByRole("button",{name:"Security Wikis"}).click();await page.getByRole("button",{name:"View"}).click();for(const title of ["Overview","Entry Points","Access Control Matrix","Vertical Helpers","Requirement Traces","Limitations"])await expect(page.locator(".wiki-section-card").getByRole("heading",{name:title})).toBeVisible();await page.getByRole("button",{name:"Open source"}).first().click();await expect(page.locator(".monaco-editor")).toBeVisible();await expect(page.locator(".evidence-line-highlight").first()).toBeVisible()});
test("capture Phase 4.8 visual matrix",async({page})=>{await commonRoutes(page);for(const [width,height] of [[1920,1080],[1366,768]]){await page.setViewportSize({width,height});localStorage.clear;await page.goto("/login");await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-login.png`,fullPage:true});await page.evaluate(()=>localStorage.setItem("security_codewiki_token","test"));await page.goto("/");await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-projects.png`,fullPage:true});await page.goto("/projects/visual");await discover(page);await page.getByRole("button",{name:"Focus analysis"}).click();await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-discover.png`,fullPage:true});await page.getByRole("button",{name:"Security Wikis"}).click();await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-wiki-library.png`,fullPage:true});await page.getByRole("button",{name:"View"}).click();await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-wiki-detail.png`,fullPage:true});await page.getByRole("button",{name:"Ask",exact:true}).click();await page.getByLabel("Question").fill("Where is access controlled?");await page.getByRole("button",{name:"Run analysis"}).click();await page.locator(".evidence-row > button").click();await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-ask-monaco.png`,fullPage:true});await page.getByLabel("Close source").click();await page.getByRole("button",{name:"Compare",exact:true}).click();await page.getByLabel("Question").fill("Compare");await page.getByRole("button",{name:"Compare models"}).click();await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-compare.png`,fullPage:true})}await page.setViewportSize({width:1366,height:768});await page.goto("/projects/visual");await page.locator(".file-sidebar").screenshot({path:"e2e/screenshots/phase4-8-sidebar-320-closeup.png"})});

test("capture completed Ask and Compare states",async({page})=>{
  await workspace(page);
  await discover(page);
  await page.getByRole("button",{name:"Focus analysis"}).click();
  for(const [width,height] of [[1920,1080],[1366,768]]){
    await page.setViewportSize({width,height});
    await page.getByRole("button",{name:"Ask",exact:true}).click();
    await page.locator('textarea[aria-label="Question"]').fill("Where is access controlled?");
    await page.getByRole("button",{name:"Run analysis"}).click();
    await page.locator(".evidence-row > button").click();
    await expect(page.locator(".monaco-editor")).toBeVisible();
    await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-ask-monaco.png`,fullPage:true});
    await page.getByLabel("Close source").click();
    await page.getByRole("button",{name:"Compare",exact:true}).click();
    await page.locator('textarea[aria-label="Question"]').fill("Compare");
    await page.getByRole("button",{name:"Compare models"}).click();
    await expect(page.locator(".model-answer")).toHaveCount(2);
    await page.screenshot({path:`e2e/screenshots/phase4-8-${width}x${height}-compare.png`,fullPage:true});
  }
});
